title: The Alchemist Encodes
description: ~ For Whom the Autist Encodes ~
destination: docs/
exclude: [README.md, LICENSE, Gemfile, jekyll-theme-tae.gempsec, _config.yml]
timezone: Europe/Amsterdam
encoding: utf-8